# https://galaxy.ansible.com/docs/using/installing.html
# ansible-galaxy install -r requirements.yml
#
# https://docs.ansible.com/ansible/devel/user_guide/collections_using.html
# ansible-galaxy collection install -r requirements.yml
---
roles:
  # https://github.com/geerlingguy/ansible-role-docker
  - src: geerlingguy.docker
